export const COLORS = {
    MOONSHOT_CORE_DARK: '#040328',
    MOONSHOT_CORE_PINK: '#D50078',
    MOONSHOT_CORE_YELLOW: '#FFEE83',
    MOONSHOT_EXTRA_DARK_BLUE: '#1B1971',
    MOONSHOT_EXTRA_BLUE: '#467BF8',
    MOONSHOT_EXTRA_LIGHT_BLUE: '#A8BDF0',
    MOONSHOT_EXTRA_BURGUNDY: '#990066',
    MOONSHOT_EXTRA_PINK: '#FCACC7',
    MOONSHOT_EXTRA_ORANGE: '#E68600',
    MOONSHOT_EXTRA_GOLD: '#FFC022',
}