export type EventCode = "oshiro"
    | "oshiro_giant"
    | "seeker"
    | "snowballs"
    | "chaser"
    | "kill"
    | "reset"
    | "wind"
    | "laughter"
    | "dashes"
    | "stamina"
    | "invincible"
    | "invisible"
    | "nostamina"
    | "zoom"
    | "earthquake"
    | "speed"
    | "slow"
    | "hiccups"
    | "icephysics"
    | "invertdpad"
    | "flipscreen"
    | "mirrorworld"
    ;