export type TiltifyEvent = "oshiro"
    | "giant oshiro"
    | "seeker"
    | "snowballs"
    | "badeline"
    | "kill player"
    | "reset level"
    | "wind"
    | "taunting laughter"
    | "unlimited dashes"
    | "infinite stamina"
    | "invincibility"
    | "invisibility"
    | "no stamina"
    | "zoom camera"
    | "earthquake"
    | "speed up time"
    | "slow down time"
    | "hiccups"
    | "ice physics"
    | "invert d-pad"
    | "flip screen"
    | "mirror world"
    ;